# Generated by Django 5.0.6 on 2025-03-13 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(default=' ', max_length=254)),
                ('admin_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='c_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=255)),
                ('cp_email', models.EmailField(max_length=254, unique=True)),
                ('cp_phone', models.CharField(max_length=15)),
                ('cp_gst_no', models.CharField(max_length=50)),
                ('cp_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.TextField()),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Freelancer', 'Freelancer')], default='Full-Time', max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='u_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(default='male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cp_verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('LLP', 'LLP'), ('Other', 'Other')], max_length=50)),
                ('industry_type', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Other', 'Other')], max_length=50)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('area_code', models.CharField(max_length=10)),
                ('registration_certificate', models.FileField(upload_to='documents/')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_pan', models.CharField(blank=True, max_length=50, null=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('rep_name', models.CharField(max_length=255)),
                ('rep_designation', models.CharField(max_length=100)),
                ('rep_phone', models.CharField(max_length=15)),
                ('rep_email', models.EmailField(max_length=254)),
                ('government_id', models.FileField(upload_to='documents/')),
                ('num_employees', models.IntegerField(blank=True, null=True)),
                ('year_establishment', models.IntegerField(blank=True, null=True)),
                ('company_description', models.TextField()),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Updated', 'Updated'), ('Verified', 'Verified')], default='Pending', max_length=20)),
                ('field_status_save', models.JSONField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.c_register')),
            ],
        ),
        migrations.CreateModel(
            name='sub_job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Freelancer', 'Freelancer')], default='Full-Time', max_length=20)),
                ('job_salary', models.IntegerField()),
                ('job_location', models.CharField(max_length=50)),
                ('job_skils', models.CharField(max_length=50)),
                ('job_experience', models.IntegerField()),
                ('job_qualification', models.CharField(max_length=50)),
                ('job_vacancy', models.IntegerField()),
                ('job_apply', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.c_register')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('notice_period', models.CharField(choices=[('Immediate', 'Immediate'), ('15 Days', '15 Days'), ('1 Month', '1 Month'), ('2 Months', '2 Months')], default='Immediate', max_length=20)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.c_register')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sub_job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.u_register')),
            ],
        ),
    ]
