# Generated by Django 5.0.6 on 2025-03-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial'),
    ]

    operations = [
    ]
