# Generated by Django 5.0.6 on 2025-03-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20250313_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_register',
            name='status',
            field=models.CharField(choices=[('New Company', 'New Company'), ('Pending', 'Pending'), ('Updated', 'Updated'), ('Verified', 'Verified')], default='New Company', max_length=20),
        ),
    ]
