# Generated by Django 5.0.6 on 2025-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
