# Generated by Django 5.0.6 on 2025-03-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_jobapplicant_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.sub_job'),
        ),
    ]
