# Generated by Django 5.0.6 on 2025-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_notification_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('user', 'User'), ('cp', 'Company')], default='user', max_length=10),
        ),
    ]
