# Generated by Django 5.0.6 on 2025-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_notification_recipient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_register',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
