# Generated by Django 5.0.6 on 2025-03-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_u_register_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cp_verify',
            name='verification_status',
            field=models.CharField(choices=[('New Company', 'New Company'), ('Pending', 'Pending'), ('Updated', 'Updated'), ('Verified', 'Verified')], default='New Company', max_length=20),
        ),
    ]
