# Generated by Django 5.0.6 on 2025-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_cp_verify_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cp_verify',
            name='status',
            field=models.CharField(choices=[('New Company', 'New Company'), ('Pending', 'Pending'), ('Updated', 'Updated'), ('Verified', 'Verified')], default='New Company', max_length=15),
        ),
    ]
