# Generated by Django 5.0.6 on 2025-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_cp_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_register',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
