# Generated by Django 5.0.6 on 2025-03-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_u_register_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_register',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
