# Generated by Django 5.0.6 on 2025-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_c_register_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_register',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='u_register',
            name='social',
            field=models.TextField(blank=True, null=True),
        ),
    ]
