# Generated by Django 5.0.6 on 2025-03-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_register',
            name='status',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Verified', 'Verified')], default='Unverified', max_length=20),
        ),
    ]
