# Generated by Django 5.0 on 2025-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_c_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cp_verify',
            name='c_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
