# Generated by Django 5.0.6 on 2025-04-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_cp_verify_c_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='website.c_register'),
        ),
    ]
