# Generated by Django 5.0.6 on 2025-04-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_tender_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('proposal_summary', models.TextField()),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='tender_proposals/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('applying_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_applications', to='website.c_register')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='website.tender')),
            ],
        ),
    ]
