# Generated by Django 5.0.6 on 2025-04-17 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_tenderapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_type',
            field=models.CharField(choices=[('Open', 'Open Tender'), ('Limited', 'Limited Tender'), ('Single', 'Single Tender')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='tender',
            name='terms_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_terms/'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.c_register'),
        ),
    ]
