# Generated by Django 5.0.6 on 2025-04-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_tender_contact_email_tender_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cp_verify',
            name='company_pan',
        ),
        migrations.RemoveField(
            model_name='cp_verify',
            name='government_id',
        ),
        migrations.RemoveField(
            model_name='cp_verify',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='cp_verify',
            name='rep_designation',
        ),
        migrations.RemoveField(
            model_name='cp_verify',
            name='tax_id',
        ),
    ]
